version: '3.8'
services:
    
    # Application & web server
    app:
        build:
            context: .
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "db"
        ports:
            - 80:80
    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root 
            MYSQL_DATABASE: mydb
        ports:
            - "6033:3306"
        volumes:
            - dbdata:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80
volumes:
    dbdata:
   
